# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.54/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Thanks
  display: shell
  authorization:
    allowAll: true
  content:
    - component: Text
      name: text
      props:
        value:
          $$jsExpression: '"Hi " + page.parameters.name + ", welcome!"'
        mode: text
    - component: Text
      name: text1
      props:
        value:
          $$jsExpression: ((page.parameters.birthday !=="null" &&
            page.parameters.birthday)?"Your birthday is " +
            page.parameters.birthday:"Select a birthday")
        mode:
          $$jsExpression: ((page.parameters.birthday === "null" ||
            !page.parameters.birthday)? "link":"text")
        href:
          $$jsExpression: '"/prod/pages/Form?name=" + page.parameters.name'
        openInNewTab: false
        loading: false
    - component: Text
      name: text2
  parameters:
    - name: name
      value: user
    - name: birthday
      value: ""
